import { AppToaster } from "@/components/ui/toast"

import GlobalNavbar from "@/components/GlobalNavbar"
import Footer from "@/components/Footer"

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body >
        <GlobalNavbar />

        <div className="p-20 mx-auto mt-10">
          {children}
        </div>
        

        <div className="fixed bottom-0 left-0 right-0">
          <Footer />
        </div>

        <AppToaster />
      </body>
    </html>
  )
}
